apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
    machineconfiguration.openshift.io/role: master
  name: 99-kvc-kmod
spec:
  config:
